# Get all people:

GET http://localhost:3001/api/persons

###

# Get person by id:

GET http://localhost:3001/api/persons/608356852a74d0d7b17d6071

###

# Add new person

POST https://mighty-plateau-33606.herokuapp.com/api/persons
Content-Type: application/json

{
  "name": "Adrien",
  "number": "111-111-1111"
}

###

# Delete person
DELETE http://localhost:3001/api/persons/4